name: OSS readiness
on:
  issues:
    types: [opened, reopened, edited, labeled]
permissions:
  contents: read
  issues: write
  pull-requests: write
jobs:
  add_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue/PR to project #2
        uses: actions/add-to-project@244f685bbc3b7adfa8466e08b698b5577571133e # v1.0.2
        with:
          project-url: https://github.com/users/raddevops/projects/2
          github-token: ${{ secrets.GITHUB_TOKEN }}
