name: Prompt Guardrails

on:
  pull_request:
    paths:
      - 'prompts/**'
      - 'scripts/**'
      - '.github/workflows/prompt-guardrails.yml'
  push:
    branches: [ main ]
    paths:
      - 'prompts/**'
      - 'scripts/**'
      - '.github/workflows/prompt-guardrails.yml'

permissions:
  contents: read

jobs:
  validate-prompts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: '3.11'

      - name: Install deps (none required)
        run: python -V

      - name: Run structural validation
        run: bash scripts/validate_prompts.sh

      - name: Verify index consistency
        run: bash scripts/check_prompt_index.sh

      - name: Verify tools index consistency  
        run: bash scripts/check_tools_index.sh

      - name: Detect stray root prompt JSON
        run: python scripts/detect_stray_prompts.py

      - name: Schema validate prompt JSON
        run: python scripts/schema_validate_prompts.py

      - name: Summary
        if: always()
        run: echo "Prompt guardrail workflow complete." 

  branch-name-policy:
    name: Branch name policy
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Check branch naming convention
        continue-on-error: true
        run: |
          bash scripts/check_branch_name.sh "${GITHUB_HEAD_REF:-$GITHUB_REF_NAME}" 
      - name: Note
        if: failure()
        run: echo "Branch name policy violated; not blocking merge."
