name: validate-prompts
on:
  pull_request:
  push:
    branches: [ main ]
permissions:
  contents: read
jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: '3.x'
      - name: Validate prompts
        run: |
          bash scripts/validate_prompts.sh
          python3 scripts/schema_validate_prompts.py
          bash scripts/check_prompt_index.sh
          python3 scripts/detect_stray_prompts.py
