name: validate-prompts
on:
  pull_request:
  push:
    branches: [ main ]
permissions:
  contents: read
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Set up Python
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
        with:
          python-version: '3.x'
      - name: Validate prompts
        run: |
          bash scripts/validate_prompts.sh
          python3 scripts/schema_validate_prompts.py
          bash scripts/check_prompt_index.sh
          python3 scripts/detect_stray_prompts.py
